excluded:
    - Pods
    - OnbanTests
    - OnbanUITests
disabled_rules:
    - trailing_whitespace
    - identifier_name
    - todo
    - force_unwrapping
    - orphaned_doc_comment
line_length:
  ignores_comments: true
